# 準備

## Googleドライブのマウント

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にDNN_codeフォルダを置くことを仮定しています．必要に応じて，パスを変更してください．

In [ ]:
import sys
sys.path.append('/content/drive/MyDrive/RabbitChallenge/深層学習Day1')

# importと関数定義

In [2]:
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    print("shape: " + str(vec.shape))
    print("")


In [3]:
np.random.rand(3, 3)

array([[0.11437576, 0.72957163, 0.64528332],
       [0.33890282, 0.51742813, 0.31923299],
       [0.81021325, 0.84546396, 0.33654767]])

実践

# 多クラス分類（2-3-4ネットワーク）

In [5]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-6 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    
    input_layer_size = 3
    hidden_layer_size=50
    output_layer_size = 6
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.93335277 0.36582779 0.77256579 0.461401   0.69068402 0.463384
  0.09447175 0.42615625 0.687944   0.63339899 0.17358256 0.20149598
  0.60397647 0.80805849 0.38253882 0.52264536 0.29140976 0.09208766
  0.12923922 0.42928919 0.17678748 0.01806706 0.78881297 0.92824842
  0.85232924 0.85102988 0.18944888 0.01610753 0.26025673 0.17223831
  0.81779847 0.66039142 0.80814806 0.28469203 0.49083541 0.55191285
  0.07987317 0.64148939 0.97787924 0.99977242 0.62483875 0.91520336
  0.26326548 0.8272375  0.69126238 0.39742957 0.54934739 0.93215711
  0.9018785  0.14647355]
 [0.80866198 0.18423497 0.67998254 0.84239598 0.7094561  0.39131937
  0.84252778 0.50129144 0.37814631 0.16013048 0.98413147 0.08732665
  0.27297494 0.93546257 0.45281228 0.77971562 0.2149111  0.00942166
  0.99333796 0.04277252 0.73033315 0.21568005 0.6474437  0.72661299
  0.80882464 0.17541161 0.68818718 0.59217328 0.95028996 0.43207854
  0.47898918 0.72688414 0.85247174 0.84785305 0.96792463 0

In [7]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-6 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    
    input_layer_size = 3
    hidden_layer_size= 5
    output_layer_size = 4
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.82170159 0.69423859 0.32978581 0.80963016 0.63349563]
 [0.303549   0.0483753  0.48834144 0.14278324 0.73894736]
 [0.97807563 0.32094065 0.25591134 0.61541109 0.92212197]]
shape: (3, 5)

*** 重み2 ***
[[0.24863542 0.8769228  0.24340611 0.82396951]
 [0.85398749 0.90928363 0.80615185 0.84388483]
 [0.2422982  0.49443733 0.65472751 0.61487176]
 [0.03586267 0.62239113 0.53038497 0.22515723]
 [0.73841218 0.01617789 0.97770196 0.12256726]]
shape: (5, 4)

*** バイアス1 ***
[0.38976826 0.4170236  0.05199498 0.45549633 0.09089713]
shape: (5,)

*** バイアス2 ***
[0.47536492 0.90916441 0.18436067 0.28082877]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[4.75279476 2.17083474 2.12619768 3.39692624 4.96865338]
shape: (5,)

*** 中間層出力1 ***
[4.75279476 2.17083474 2.12619768 3.39692624 4.96865338]
shape: (5,)

*** 総入力2 ***
[ 7.81685463 10.2967736  11.14286327  8.71009687]
shape: (4,)

*** 出力1 ***
[0.02314258 0.27632932 0.64398989 0.05653821]
shape: (4,)

出力合計: 1.0

##### 結果表示 

# 回帰（2-3-2ネットワーク）

In [ ]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    input_layer_size = 3
    hidden_layer_size=5
    output_layer_size = 4
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
    
    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("二乗誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[8.45487948e-01 2.19540108e-01 9.44712712e-01 7.59633897e-01
  4.05406854e-01 3.50906875e-01 4.50875012e-01 6.93673192e-01
  2.78176490e-01 3.70632471e-01 4.26333795e-01 5.83044590e-01
  9.88930757e-01 8.51389143e-01 6.03923184e-01 5.83781496e-01
  6.05358191e-01 8.66426792e-01 4.72049503e-01 1.09277321e-01
  5.14961817e-01 3.77692978e-02 7.03694291e-01 4.92406094e-01
  2.60836384e-01 2.58643198e-02 9.52511417e-01 5.55197952e-01
  8.70169925e-01 3.85212729e-01 9.67941210e-01 2.15969580e-02
  1.16836251e-01 5.53032658e-01 9.05490690e-01 2.90347460e-01
  7.05012657e-01 4.39086392e-01 5.10063088e-01 1.72073054e-01
  4.71925919e-01 3.33830914e-02 6.43430854e-01 9.25674375e-01
  2.65544113e-01 8.58078443e-01 1.05717608e-01 6.22025106e-01
  7.24895239e-01 6.63653190e-01]
 [1.84144766e-01 9.85893395e-01 5.32368575e-01 9.16466643e-01
  3.68253762e-01 2.19427852e-01 2.68038677e-01 7.94433582e-01
  5.86631936e-01 2.30412623e-01 8.17386375e-01 8.32089277e-01
  

# 2値分類（2-3-1ネットワーク）

In [ ]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-20-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1]
    ])
    network['W2'] = np.random.rand(10, 20)
    network['W3'] = np.random.rand(20, 1)

    network['b1'] = np.random.rand(10)
    network['b2'] =np.random.rand(20)
    network['b3'] =np.random.rand(1)

    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2, W3 = network['W1'], network['W2'],network['W3']
    b1, b2, b3 = network['b1'], network['b2'],network['b3']

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層1の総出力
    z1 = functions.relu(u1)
    # 隠れ層２層への総入力
    u2 = np.dot(z1, W2) + b2
    # 隠れ層2の出力
    z2 = functions.relu(u2)
    
    u3 = np.dot(z2, W3) + b3
    z3 = functions.sigmoid(u3)
    y = z3    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2.,2.,4.,5.])

# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[1.44958992 4.64085047 7.08409646 1.65555511 4.28835722 7.0912002
 1.88070272 4.30705587 7.60101133 2.05743603]
shape: (10,)

*** 中間層出力1 ***
[1.44958992 4.64085047 7.08409646 1.65555511 4.28835722 7.0912002
 1.88070272 4.30705587 7.60101133 2.05743603]
shape: (10,)

*** 総入力2 ***
[25.76026363 18.34305517 14.56902644 26.63056869 29.37097957 19.64951286
 16.56686913 15.55875883 11.50650918 19.40816327 16.63060366 20.56197736
 24.49918331 19.80296373 25.09245768 16.06579532 20.1859192  18.7403375
 20.3862084  21.45431152]
shape: (20,)

*** 出力1 ***
[1.]
shape: (1,)

出力合計: 1.0

##### 結果表示 #####
*** 中間層出力 ***
[1.44958992 4.64085047 7.08409646 1.65555511 4.28835722 7.0912002
 1.88070272 4.30705587 7.60101133 2.05743603]
shape: (10,)

*** 出力 ***
[1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 交差エントロピー誤差 ***
-9.999999505838704e-08
shape: ()

